## Shark Attack Data

Before touching the data, answer the following:

1. What is the response variable? Is this a regression or classification problem?

The response variable is whether an incident was fatal or not. Therefore, this is a classification problem.

2. What performance metric will you use, and why is it appropriate?



3. What is a sensible baseline to beat (e.g., predicting the mean, a simple rule, a published benchmark)?

A sensible baseline to beat is ...

4. Are there any domain-specific constraints on errors? Is over-prediction or under-prediction more costly?

In [1]:
import pandas as pd
import numpy as np

In [25]:
shark_df = pd.read_excel("GSAF5.xls",engine='xlrd')
shark_df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,24th May,2026.0,Unprovoked,Australia,Queensland,Kennedy Shoal,Spearfishing,Michael Jensz,M,39,...,Undetermined Bull shark most likely,Simon de Marchi: 9 News: 7 News: ABC News:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17th May,2026.0,Questionable,USA,Maryland,Assateague State Park,Surfing,Brendan Oster,M,?,...,Blue fish bite most probable,Keithe Cowley: Delmarva Now:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16th May,2026.0,Unprovoked,Australia,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,Steven Mattaboni,M,38,...,Great White Shark,ABC News: 9 News: 7 News: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,14th April,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
shark_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7090 entries, 0 to 7089
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       7090 non-null   object
 1   Year       7088 non-null   float64
 2   Type       7072 non-null   object
 3   Country    7040 non-null   object
 4   State      6603 non-null   object
 5   Location   6523 non-null   object
 6   Activity   6507 non-null   object
 7   Name       6872 non-null   object
 8   Sex        6512 non-null   object
 9   Age        4096 non-null   object
 10  Injury     7054 non-null   object
 11  Fatal Y/N  6529 non-null   object
 12  Time       3563 non-null   object
 13  Species    3959 non-null   object
 14  Source     7070 non-null   object
dtypes: float64(1), object(14)
memory usage: 831.0+ KB

In [26]:
# Drop columns
cols_to_drop = [15,16,17,17,18,19,20,21,22]
shark_df.drop(shark_df.columns[cols_to_drop], axis=1, inplace=True)
shark_df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source
0,24th May,2026.0,Unprovoked,Australia,Queensland,Kennedy Shoal,Spearfishing,Michael Jensz,M,39,Bite wounds to the head,Y,1100hrs,Undetermined Bull shark most likely,Simon de Marchi: 9 News: 7 News: ABC News:
1,17th May,2026.0,Questionable,USA,Maryland,Assateague State Park,Surfing,Brendan Oster,M,?,Bite wound to the hand,N,?,Blue fish bite most probable,Keithe Cowley: Delmarva Now:
2,16th May,2026.0,Unprovoked,Australia,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,Steven Mattaboni,M,38,Severe injuries both legs,Y,1000hrs,Great White Shark,ABC News: 9 News: 7 News: Simon De Marchi
3,14th April,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,Leg strpped off flesh later amputated in hospital,N,?,Unknown,The U.S. Sun: Simon De Marchi
4,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,Bite wound to R ankle,N,?,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...

In [35]:
# Convert to string
shark_df.astype('str')

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Fatal Y/N,Time,Species,Source
0,24th May,2026.0,Unprovoked,Australia,Queensland,Kennedy Shoal,Spearfishing,Michael Jensz,M,39,Bite wounds to the head,Y,1100hrs,Undetermined Bull shark most likely,Simon de Marchi: 9 News: 7 News: ABC News:
1,17th May,2026.0,Questionable,USA,Maryland,Assateague State Park,Surfing,Brendan Oster,M,?,Bite wound to the hand,N,?,Blue fish bite most probable,Keithe Cowley: Delmarva Now:
2,16th May,2026.0,Unprovoked,Australia,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,Steven Mattaboni,M,38,Severe injuries both legs,Y,1000hrs,Great White Shark,ABC News: 9 News: 7 News: Simon De Marchi
3,14th April,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,Leg strpped off flesh later amputated in hospital,N,?,Unknown,The U.S. Sun: Simon De Marchi
4,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,Bite wound to R ankle,N,?,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7085,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,nan,FATAL,Y,nan,nan,"H. Taunton; N. Bartlett, p. 234"
7086,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,nan,Pearl diving,Ahmun,M,nan,FATAL,Y,nan,nan,"H. Taunton; N. Bartlett, pp. 233-234"
7087,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,nan,FATAL,Y,nan,nan,"F. Schwartz, p.23; C. Creswell, GSAF"
7088,1883-1889,0.0,Unprovoked,PANAMA,nan,"Panama Bay 8ºN, 79ºW",nan,Jules Patterson,M,nan,FATAL,Y,nan,nan,"The Sun, 10/20/1938"
7089,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,nan,nan,S.W. Baker

In [36]:
from sklearn.model_selection import train_test_split

response_var = 'Fatal Y/N'  # replace

X = shark_df.drop(columns=response_var)
y = shark_df[response_var]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f'Training   : {X_train.shape[0]} rows')
print(f'Test       : {X_test.shape[0]} rows')

Training   : 5672 rows
Test       : 1418 rows

In [15]:
# Explore the Name variable
print(shark_df['Name'].nunique())
print(shark_df['Name'].is_unique)
print(shark_df['Name'].head())

5804
False
0                Michael Jensz
1                Brendan Oster
2             Steven Mattaboni
3    Not stated - on honeymoon
4         Oliver Tokic-Bensley
Name: Name, dtype: object

In [11]:
# Explore null values
shark_df.isnull().sum()

Date                 0
Year                 2
Type                18
Country             50
State              487
Location           567
Activity           583
Name               218
Sex                578
Age               2994
Injury              36
Fatal Y/N          561
Time              3527
Species           3131
Source              20
pdf                291
href formula       296
href               294
Case Number        292
Case Number.1      293
original order     291
Unnamed: 21       7089
Unnamed: 22       7088
dtype: int64

In [37]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

# num_features = [...]  # fill in
cat_features = ['Date', 'Year', 'Type',
                'Country', 'State', 'Location', 'Activity', 'Injury']  # fill in (empty list if none)

# numeric_pipeline = Pipeline(
#     [('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler())]
# )

categorical_pipeline = Pipeline(
    [
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore')),
    ]
)

preprocessor = ColumnTransformer(
    [
        #('num', numeric_pipeline, num_features),
        ('cat', categorical_pipeline, cat_features),
    ]
)

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print(f'Processed training shape: {X_train_processed.shape}')
print(f'Processed test shape    : {X_test_processed.shape}')

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['datetime', 'int', 'str']